In [1]:
%load_ext autoreload
%autoreload 1
import sys
import numpy as np
import cv2
import torch

sys.path.append("/liujinxin/code/lhc/wy/openpi/src")
sys.path.append("/liujinxin/code/lhc/wy/openpi/packages/openpi-client/src")
sys.path.append("/liujinxin/code/lhc/wy/openpi")

from openpi.training import config as _config
from openpi.shared import download
from openpi.policies import policy_config as _policy_config

config = _config.get_config("pi0_bimanual_tool")
checkpoint_dir = download.maybe_download("/liujinxin/code/lhc/openpi/checkpoints/pi0_bimanual_tool/tool_filtered_678/15000")
policy = _policy_config.create_trained_policy(config, checkpoint_dir)

head_img = cv2.imread("/liujinxin/code/lhc/wy/openpi/rtc_debug/front_head_img.png")
left_img = cv2.imread("/liujinxin/code/lhc/wy/openpi/rtc_debug/left_hand_img.png")
right_img = cv2.imread("/liujinxin/code/lhc/wy/openpi/rtc_debug/right_hand_img.png")
state = np.load("/liujinxin/code/lhc/wy/openpi/rtc_debug/state.npy")
previous_actions = np.array([0])

instruction = "Put the round tape on the hook"
delay = 6
action_exec_s = 10

data = {
    "prompt": f"{instruction}",
    # "state": torch.from_numpy(state).to(dtype=torch.bfloat16),
    "state": torch.from_numpy(state).to(dtype=torch.float32),
    # "state": torch.from_numpy(state).to(dtype=torch.float32).zero_(),
    "front_head": torch.from_numpy(head_img),
    "left_hand": torch.from_numpy(left_img),
    "right_hand": torch.from_numpy(right_img),
}

/liujinxin/conda3/envs/openai_lhc/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-09-01 09:16:17.738736: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-09-01 09:16:17.738913: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-09-01 09:16:17.898888: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-09-01 09:17:00.578077: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warnin

In [3]:
%aimport openpi.models.pi0
%aimport openpi.policies.policy
%aimport openpi.policies.policy_config
config = _config.get_config("pi0_bimanual_tool")
checkpoint_dir = download.maybe_download("/liujinxin/code/lhc/openpi/checkpoints/pi0_bimanual_tool/tool_filtered_678/15000")
# checkpoint_dir = download.maybe_download("/liujinxin/code/lhc/openpi/checkpoints/pi0_bimanual/tool_filtered_678/20000")
policy = _policy_config.create_trained_policy(config, checkpoint_dir)

In [ ]:
policy._output_transform

CompositeTransform(transforms=[Unnormalize(norm_stats={'state': NormStats(mean=array([-1.39814147e-04, -4.86703975e-05, -5.00832160e-04,  3.80918173e-05,
        8.82984255e-04,  5.29210010e-05,  6.70640220e-05, -1.64848000e-01,
        7.68756643e-02,  3.27995978e-02, -2.96533555e-02, -1.73564687e-01,
        3.73103380e-01,  1.58386201e-01,  3.56420904e-01,  4.74421009e-02,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00]), std=array([1.00713922e-03, 8.14107829e-04, 3.46963265e-04, 8.37308122e-04,
       3.49176611e-04, 8.15438223e-04, 7.17441493e-04, 2.18300208e-01,
       6.53988644e-02, 2.06424966e-01, 2.26095900e-01, 1.20679080e-01,
       2.67902464e-01, 1.31154522e-01, 3.64534944e-01, 1.77853145e-02,
       0.00000000e+00, 0.000000

In [4]:
rng = jax.random.PRNGKey(42)
policy._rng = rng

NameError: name 'jax' is not defined

In [ ]:
import time

previous_actions = np.array([0])

start = time.time()
with torch.inference_mode():
    action_rtc = policy.infer_rtc(data, is_first_step=True, previous_actions=previous_actions)
end = time.time()
print(f"Inference time: {end - start:.4f} seconds")

TypeError: sub got incompatible shapes for broadcasting: (32,), (1600,).

In [ ]:
start = time.time()
with torch.inference_mode():
    action = policy.infer(data)
end = time.time()
print(f"Inference time without RTC: {end - start:.4f} seconds")

v_t norm 40.75, a_est_1_norm 7.273569107055664
v_t norm 40.75, a_est_1_norm 7.289752960205078
v_t norm 40.75, a_est_1_norm 7.26961088180542
v_t norm 40.5, a_est_1_norm 7.27787446975708
v_t norm 40.5, a_est_1_norm 7.235125541687012
v_t norm 40.25, a_est_1_norm 7.214241981506348
v_t norm 40.25, a_est_1_norm 7.177411079406738
v_t norm 40.25, a_est_1_norm 7.154685974121094
v_t norm 40, a_est_1_norm 7.0991926193237305
v_t norm 39.75, a_est_1_norm 7.071256160736084
result norm: 7.071706771850586
Inference time without RTC: 8.1217 seconds


In [ ]:
action["actions"].shape

(50, 16)

In [ ]:
np.equal(action_rtc["actions"], action["actions"])[0, 0] == True

True

In [ ]:
action_rtc["actions"].shape

(50, 16)

In [ ]:
action["actions"]

array([[-1.02906611e-03, -5.27508617e-04, -6.70986982e-04,
        -7.25547960e-04,  1.02462743e-03, -4.14051844e-04,
        -1.01003346e-03, -9.90904261e-04,  2.10246752e-03,
         1.55610636e-03,  2.47519753e-03,  1.11055438e-03,
        -1.70737595e-02,  3.47285500e-04,  5.70861873e-02,
         5.68599603e-02],
       [-1.02924927e-03, -5.27324727e-04, -6.70879142e-04,
        -7.24012988e-04,  1.02482527e-03, -4.15132552e-04,
        -1.00999396e-03, -1.05204611e-03,  2.96885158e-03,
         1.36756216e-03,  5.18975882e-03,  1.54039362e-03,
        -1.88952219e-02, -1.19333082e-04,  5.63937999e-02,
         5.68717598e-02],
       [-1.02925295e-03, -5.27432005e-04, -6.70922319e-04,
        -7.26259150e-04,  1.02488101e-03, -4.15294386e-04,
        -1.00996535e-03, -2.04834169e-03,  3.73192131e-03,
         2.39340232e-03,  7.22366194e-03,  1.56467410e-03,
        -1.84754300e-02,  2.54720490e-04,  5.52326077e-02,
         5.68605573e-02],
       [-1.02932445e-03, -5.27284301e

In [ ]:

previous_actions_rtc = np.ones((50, 32))
import math
# move weight calculation outside of the inference code for compilation requirements
horizon = 50
delay = 6
action_exec_s = 10
# print("horizon:", horizon)
# print("delay:", delay)
weights = np.zeros(horizon)
for i in range(horizon):
    if i < delay:
        weights[i] = 1
    elif delay <= i < horizon - action_exec_s:
        c_i = (horizon - action_exec_s - i) / (horizon - action_exec_s - delay + 1)
        weights[i] = c_i * (math.exp(c_i) - 1) / (math.exp(1) - 1)
    else:
        weights[i] = 0
weight_vector = np.repeat(weights, 32)

# weights_expanded = torch.diag(weight_vector)
# weights_expanded = weights_expanded.numpy()

previous_actions_padded = np.pad(action["actions"], ((0, 0), (0, 16)), 'constant', constant_values=0)
start = time.time()
with torch.inference_mode():
    action_rtc = policy.infer_rtc(data, previous_actions=previous_actions_padded, weight_vector=weight_vector)
end = time.time()
print(f"Inference time: {end - start:.4f} seconds")

grad_back_norm=1.1483867168426514
prev_a_norm=7.04224967956543, v_t_norm=40.75, a_est_1_norm=7.273569107055664, diff_norm=0.4338844120502472, bias_norm=0.03311266750097275, scaling_factor=5.0
grad_back_norm=0.9821302890777588
prev_a_norm=7.04224967956543, v_t_norm=40.75, a_est_1_norm=7.291375160217285, diff_norm=0.3319857716560364, bias_norm=0.016401506960392, scaling_factor=5.0
grad_back_norm=1.0569169521331787
prev_a_norm=7.04224967956543, v_t_norm=40.75, a_est_1_norm=7.268202304840088, diff_norm=0.27392977476119995, bias_norm=0.010430867783725262, scaling_factor=4.249998569488525
grad_back_norm=1.2051581144332886
prev_a_norm=7.04224967956543, v_t_norm=40.5, a_est_1_norm=7.278035640716553, diff_norm=0.23342472314834595, bias_norm=0.00541218277066946, scaling_factor=2.761904001235962
grad_back_norm=1.4251089096069336
prev_a_norm=7.04224967956543, v_t_norm=40.5, a_est_1_norm=7.229621887207031, diff_norm=0.2207922637462616, bias_norm=0.004146161023527384, scaling_factor=2.16666626930236

In [ ]:
action_rtc["actions"]

array([[-1.02906895e-03, -5.27494733e-04, -6.70919442e-04,
        -7.25178011e-04,  1.02460324e-03, -4.14004007e-04,
        -1.01003595e-03, -1.47482573e-03,  2.12906101e-03,
         1.52352871e-03,  3.04466149e-03,  1.05551822e-03,
        -1.73525808e-02,  4.14379025e-04,  5.71953542e-02,
         5.68528525e-02],
       [-1.02920319e-03, -5.27350013e-04, -6.70860340e-04,
        -7.24104859e-04,  1.02484508e-03, -4.14771878e-04,
        -1.00999607e-03, -1.19545541e-03,  3.01698000e-03,
         1.66051594e-03,  5.39842778e-03,  1.59750224e-03,
        -1.88271451e-02, -8.39823116e-05,  5.67466619e-02,
         5.68672835e-02],
       [-1.02916668e-03, -5.27373212e-04, -6.70919919e-04,
        -7.26408935e-04,  1.02488074e-03, -4.14829662e-04,
        -1.00995901e-03, -1.96703273e-03,  3.77010513e-03,
         2.44921679e-03,  7.40191853e-03,  1.72923804e-03,
        -1.92048489e-02,  5.07907802e-04,  5.51987068e-02,
         5.68436040e-02],
       [-1.02927487e-03, -5.27277984e

In [ ]:
action_diff = action_rtc["actions"] - action["actions"]
action_diff[:6, 8:16]

array([[ 2.65934900e-05, -3.25776561e-05,  5.69463958e-04,
        -5.50361612e-05, -2.78821289e-04,  6.70935246e-05,
         1.09166956e-04, -7.10787645e-06],
       [ 4.81284151e-05,  2.92953785e-04,  2.08668963e-04,
         5.71086184e-05,  6.80767390e-05,  3.53507701e-05,
         3.52862018e-04, -4.47635059e-06],
       [ 3.81838226e-05,  5.58144776e-05,  1.78256582e-04,
         1.64563942e-04, -7.29418860e-04,  2.53187312e-04,
        -3.39009108e-05, -1.69533032e-05],
       [ 1.23839498e-05,  1.15426861e-04,  3.78218119e-04,
         6.11915111e-05, -6.02771991e-05,  4.01324993e-05,
         1.38486081e-04,  3.53485383e-06],
       [ 4.03853655e-05, -1.08961813e-05,  1.35043178e-04,
         1.81649134e-04,  7.62490872e-05,  3.99071680e-05,
         2.30272367e-04,  3.30796159e-06],
       [-3.64007570e-05, -4.50408565e-06,  3.78385669e-04,
         8.80573899e-05,  1.67959904e-04,  5.57265109e-05,
        -3.07646463e-04, -8.41833816e-06]])

In [ ]:
action["actions"][:6, 8:16]

array([[ 0.00210247,  0.00155611,  0.0024752 ,  0.00111055, -0.01707376,
         0.00034729,  0.05708619,  0.05685996],
       [ 0.00296885,  0.00136756,  0.00518976,  0.00154039, -0.01889522,
        -0.00011933,  0.0563938 ,  0.05687176],
       [ 0.00373192,  0.0023934 ,  0.00722366,  0.00156467, -0.01847543,
         0.00025472,  0.05523261,  0.05686056],
       [ 0.00387353,  0.0015385 ,  0.00807703,  0.00199639, -0.0197556 ,
         0.00065772,  0.05262723,  0.05687237],
       [ 0.00403416,  0.00238835,  0.00926508,  0.00215146, -0.01918928,
         0.0005962 ,  0.0502362 ,  0.05689565],
       [ 0.00426053,  0.0019197 ,  0.00998856,  0.0019954 , -0.01944647,
         0.00106867,  0.04977538,  0.05686346]])

In [ ]:
action_frame_diff = action["actions"][1:, 8:16] - action["actions"][:-1, 8:16]

In [ ]:
np.mean(action_frame_diff, axis=0)

array([ 9.20507088e-05,  3.66815751e-05,  3.41611224e-04,  3.76517120e-05,
       -5.70728906e-05,  2.98662865e-05, -2.46396195e-04, -1.97410960e-06])

In [ ]:
np.std(action_frame_diff, axis=0)

array([2.59507723e-04, 6.04725609e-04, 1.00118682e-03, 2.74754054e-04,
       9.24662795e-04, 3.18928371e-04, 8.98786528e-04, 3.83797784e-05])